# -*- coding: utf-8 -*-
"""SQlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgkccoxHPmN8D1Uvfgc7CdgA-JI-ULhx

# Introdução ao SQlite com python
# Inserindo Dados

* Criando um banco de dados
* Criando colunas
* Inserindo Informações no banco de dados
* Visualizando informações dentro do SQlite.
"""

import sqlite3
banco = sqlite3.connect('banco_main.db')

# objeto cursos que recebe o objeto que cria o banco
cursor = banco.cursor()

# Criando um banco de dados com o nome pessoa, com as seguintes colunas nome, idade e email.
cursor.execute('CREATE TABLE pessoas (nome text, idade integer, email text)')

# Inserindo informação na tabela pessoas
cursor.execute('INSERT INTO pessoas VALUES("Aline Silva",90,"AlineSilva.com.br")')

# Enviando essas informações para o nosso banco de dados com o comando commit
banco.commit()
print('Tabela atualizada !')

# Para podemos visualizar os dados inserido dentro da tabela:
cursor.execute('SELECT * FROM pessoas')
print(cursor.fetchall())

"""# Excluindo no SQlite"""

try:
  cursor.execute("DELETE from pessoas WHERE idade = 90")
  banco.commit()
  print('Dados deletados com sucesso.')
  cursor.execute('SELECT * FROM pessoas')
  print(cursor.fetchall())
except sqlite3.Error as erro:
    print(f'Erro ao deletar dados.{erro}')

"""# Inserindo dados no SQlite, através de variaveis dinamincas

"""

# Informações de um formulario
nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
email = input('Digite seu email: ')

try:
  cursor.execute("INSERT INTO pessoas VALUES ('"+nome+"',"+str(idade)+",'"+email+"')")
  print('Dados inseridos com sucesso.')
  cursor.execute('SELECT * From pessoas')
  print(cursor.fetchall())
  # cursor.execute('INSERT INTO pessoas VALUES("Aline Silva",90,"AlineSilva.com.br")')
except sqlite3.Error as erro:
    print(f'Erro ao inserir dados. {erro}')

"""# Atualizando os danos no SQlite

### Atualizando nome
"""

# Atualizando somente o nome
try:
  cursor.execute("UPDATE pessoas SET nome = 'Eduardo' WHERE idade = 22")
  print('Dados atualizandos com sucesso...')
  cursor.execute('SELECT * FROM pessoas')
  print(cursor.fetchall())
except sqlite3.Error as erro:
    print(f'Erro ao atualizar os dados. {erro}')

"""### Atualizando nome, idade e email"""

# Alterando nome,idade e email
try:
  cursor.execute("UPDATE pessoas SET nome = 'Eduardo' WHERE idade = 22")
  cursor.execute("UPDATE pessoas SET idade = 25 WHERE nome = 'Eduardo'")
  cursor.execute("UPDATE pessoas SET email = 'edu.com.br' WHERE nome = 'Eduardo'")
  print('Dados atualizandos com sucesso...')
  cursor.execute('SELECT * FROM pessoas')
  print(cursor.fetchall())
except sqlite3.Error as erro:
    print(f'Erro ao atualizar os dados. {erro}')